apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:oRBuFo0dDmRyz1yJJUndesbpqp5WmzbFGx/Rq/xvFdaCa7BnMNWwVFxAxSDrnsYgdWqpY8beWap2IG9+LuED1rMnilFfcrzX9g3LJqY/3W8CJhOE32aGl/nCK/tpB970zbjdJakX/BDv0ljAg5FT1OF8JhggqyOe8yJCShD+ZYxq9WmVU4C5jEnu2W75ZjytkDwSoylNZGuc/OXvA84tnT/wqJpKmooIJw8pzT0V5JkdcmUo6K9OYD4YNoozyRIOsIUZ23z2dWdkpyK9kh9ISMkOVpGSBxT7xslouUuao31HndCgKrV2lbQK8LFuT12QEOFvOuycKhYl4CuiMwaOmMrxrUtSR473xhN+CsU63zg78e/JAqDNFimIWDyLEMTu,iv:LwooNvpGll2oK0FVryhPChBqukzF7Dtgq17OF74IB74=,tag:HIiFpDKQbo3MyMq1yFcqQg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Nr8YqBN4HYeOCBQcFSYomvN/Xd/xsVpaiklGNn9JB3I3wvJRNN25rc59CgnA1ul3yTNSGxytiqCpMSl+5Pu+Nmj2dwYTRpijn9BE3fVCocUovEKC6bB0FsAVHRPeNkAgxPfTmfYIx1ayyr5BBXmVcavziE+OK5gF2qNrkkJNYAUE3ttr0PAy+wQ5hZKbvf5NqKGuYCErJDrqRITieLkd0H52hBjUvQWIjEag0tz6PsFtiKSvTgwPQmoMhg3V4iL7bxcv3hHJN5P6bFT1cQ==,iv:RLC+j4wQQD2cddZRfcIH4RxkiRlVLy7T9ViDfxJZ/RY=,tag:YucgIfocngjzuTsF8DO/4w==,type:str]
    known_hosts: ENC[AES256_GCM,data:RLrGCxTFO2eqhaY1jeQJ2Fi+Um1lCqQpvgpCL1rAF/MTM47UrGRlUVzetuwwYxjpr2wnSfRrsnDzIF32pNBrpnwhh7jYD+aSnK8N/7pfq8gckGGYulQPX2lQ/vuRdRsOuA3KL8TB5WhBgmWdjYesqGUv51nBtsMmHi41Xv3SQDNCUmJuNiAw/lRRjOqSjczDKD6CZ1ZjG0U9KBLmmUC1G2JTfyTBZcudjwh6,iv:B28ZJjyU748SWWnWV26LnVq5W8OSpSZKbUmlGotFy8o=,tag:1Rzvi6i1kOf/uBLdNfPwIQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18pglxfcmalplgnkpzg5v7mg9mqjwkmmc8gxjecat4j5mp5qtpgsqj6x9kq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIT2Zpb21TZElCbzNPY3ZE
            Y1lCSGxscTRMWU9lSklyK2hXQk85blN5bVRRCi8yMG8wbW8xUythQWtSbHZ3ajZt
            aHpMbWFtNURjTEdJQXBtbm01MzFxRUkKLS0tIDBqNjlVWWVLWE9Bc2drOEdpZ3E3
            SFdmLzQ3SmhmMXFaNlp3U2xKUWMyVkkKM1stNKqgQwn5YZb5+/yzVE11EY/5O2Gs
            9w1nAsp4vHzaB3rS/Jq7T0b/SxyUCu+k5wZ6yDYYl1RYjz+aZOlSPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-26T16:34:26Z"
    mac: ENC[AES256_GCM,data:FZHLxyr7ihnf7YCckx++m3T2V/enu9V6jKfEHILvV7dV8bs9QyXmwzn8/S10Ttxi/UDDpkK1IJs0n2nR+fuJmWQr4h8ISMbdCAYOv24YxGci7/humwvjOxqlRlzATGRhMDwPM8s5MqlO/ppYqmx9MUrmfIkt6GxdAxQoOA4bjEs=,iv:F8qO/pCVjCSdE7Ue8Maz8H5cquTd/BjzVukzRqr/dsM=,tag:WWrpVMnP+0PIAGqswLy06g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
